{{- if and .Values.neo4j.enabled .Values.neo4j.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app.kubernetes.io/component: data
    app.kubernetes.io/instance: my-amundsen
    app.kubernetes.io/name: neo4j
  name: data-my-amundsen-neo4j-data
  namespace: amundsen
spec:
  accessModes:
  - {{ default "ReadWriteOnce" .Values.neo4j.persistence.accessMode }}
  resources:
    requests:
      storage: {{ default "3Gi" .Values.neo4j.persistence.size }}
  storageClassName: {{ default "standard" .Values.neo4j.persistence.storageClass }}
{{- end }}
