apiVersion: v1
description: Amundsen is a metadata driven application for improving the productivity of data analysts, data scientists and engineers when interacting with data.
name: amundsen
version: 2.1.2
icon: https://github.com/amundsen-io/amundsen/blob/master/docs/img/logos/amundsen_logo_on_light.svg
home: https://github.com/amundsen-io/amundsen
maintainers:
  - name: Amundsen TSC
    email: amundsen-tsc@lists.lfai.foundation
sources:
  - https://github.com/amundsen-io/amundsen
keywords:
  - metadata
  - data
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: elasticsearch
    version: 19.9.5
    repository:  https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: neo4j
    version: 5.7.0
    repository:  https://helm.neo4j.com/neo4j
    condition: neo4j.chartEnabled
